Fix TMP_DIR as string
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 652, in <module>
    CACHE_DB = TMP_DIR.rstrip('/') + '/zbx-hpmsa.cache.db'
AttributeError: 'list' object has no attribute 'rstrip'

TMP_DIR need to be a string.